### PR TITLE
fix(themes): 🐞 Enhancements For `salla-breadcrumb` styles

### PR DESCRIPTION
**Pull request by jalmatari**
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* Enhancements

What is the current behaviour? (You can also link to an open issue here)

* salla-breadcrumb not covers loyalty & user-profile background

What is the new behaviour? (You can also link to the ticket here)

* consider loyalty & user-profile breadcrumb backgrounds

Does this PR introduce a breaking change?

* No

Screenshots (If appropriate)

*

### CODE REVIEW

**Comment by SallaDev** [comment]
**Approve:**
- can not merge pr (https://github.com/SallaApp/theme-raed/pull/351) needs at least `one approve ❗️`


**Status Checks:**
- `Codacy Static Code Analysis` of (https://github.com/SallaApp/theme-raed/pull/351) is in progress, please try after it's finished ⌛️.

Merge by: @jalmatari

**Comment by SallaDev** [comment]
**Approve:**
- can not merge pr (https://github.com/SallaApp/theme-raed/pull/351) needs at least `one approve ❗️`



Merge by: @jalmatari

**Review by egkrinkel — APPROVED** [review]

**Comment by SallaDev** [comment]
https://github.com/SallaApp/theme-raed/pull/351 is been merged ✅

-------------------

Merge by: @jalmatari

**Pull request merged**
