### PR TITLE
refactor(themes): TD-174 custom main menu

### PR DESCRIPTION
**Pull request by jalmatari**
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* Refactor

What is the current behaviour? (You can also link to an open issue here)

* Menus dom coming cached from backend

What is the new behaviour? (You can also link to the ticket here)

* Use Menus from api request
* Add fallback for brand title when is not set in brand setting in merchant dashboard
* Refactor isElementLoaded for performance
* Minor refactoring of main-menu.js

Does this PR introduce a breaking change?

* No

Screenshots (If appropriate)

*

### CODE REVIEW

**Comment by SallaDev** [comment]
**Approve:**
- can not merge pr (https://github.com/SallaApp/theme-raed/pull/349) needs at least `one approve ❗️`


**Status Checks:**
- Please make sure  `Codacy Static Code Analysis` of (https://github.com/SallaApp/theme-raed/pull/349) is passed  ❌.

Merge by: @jalmatari

**Review by W-O-X-Y — APPROVED** [review]

**Comment by SallaDev** [comment]
https://github.com/SallaApp/theme-raed/pull/349 is been merged ✅

-------------------

Merge by: @jalmatari

**Pull request merged**
