### PR TITLE
feat(TD-578): 📆 Support Order Option Appointment Field

### PR DESCRIPTION
**Pull request by jalmatari**
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* Chore

What is the current behaviour? (You can also link to an open issue here)

* We are showing the price on the dom

What is the new behaviour? (You can also link to the ticket here)

* Show the price from the component

Does this PR introduce a breaking change?

* No

Screenshots (If appropriate)

*

### CODE REVIEW

**Comment by SallaDev** [comment]
**Approve:**
- can not merge pr (https://github.com/SallaApp/theme-raed/pull/410) needs at least `one approve ❗️`



Merge by: @jalmatari

**Review by devlomingo — APPROVED** [review]

**Comment by SallaDev** [comment]
https://github.com/SallaApp/theme-raed/pull/410 is been merged ✅

-------------------

Merge by: @jalmatari

**Pull request merged**
