### PR TITLE
Fix Comments - Themes enhances fixes

### PR DESCRIPTION
**Pull request by egkrinkel**
Related: https://github.com/SallaApp/Store/pull/4353

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* 

What is the current behaviour? (You can also link to an open issue here)

* 

What is the new behaviour? (You can also link to the ticket here)

* 

Does this PR introduce a breaking change?

* 

Screenshots (If appropriate)

*

### CODE REVIEW

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/198 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/198 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/198 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/198 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/198 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/198 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/198 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/198 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/198 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/198 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/198 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/198 has been synced from master..✅

**Comment by jalmatari** [comment]
No more need for it

**Pull request closed without merging**
