### PR TITLE
feat(themes): ⭐️ Enhanced reviews system phase 2

### PR DESCRIPTION
**Pull request by eslamoo**
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* Enhancements

What is the current behaviour? (You can also link to an open issue here)

* Customers Can't edit/delete reviews

What is the new behaviour? (You can also link to the ticket here)

* Customers Can edit/delete reviews

Does this PR introduce a breaking change?

* No

Screenshots (If appropriate)

*

### CODE REVIEW

**Comment by SallaDev** [comment]
> The branch `feature/STORE-1842-enhance-reviews-system` of https://github.com/SallaApp/theme-raed/pull/435 Branch is up-to-date..✅

**Review by jalmatari — APPROVED** [review]

**Review by jalmatari — APPROVED** [review]

**Review by jalmatari — APPROVED** [review]

**Comment by SallaDev** [comment]
https://github.com/SallaApp/theme-raed/pull/435 is been merged ✅

-------------------

Merge by: @jalmatari

**Pull request merged**
