### PR TITLE
fix(themes): Upgrade Twilight Components

### PR DESCRIPTION
**Pull request by ashrafreda**
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* 

What is the current behaviour? (You can also link to an open issue here)

* 

What is the new behaviour? (You can also link to the ticket here)

* 

Does this PR introduce a breaking change?

* 

Screenshots (If appropriate)

*

### CODE REVIEW

**Review by Ahmed-Basalib10 — APPROVED** [review]

**Review by jalmatari — APPROVED** [review]

**Comment by SallaDev** [comment]
https://github.com/SallaApp/theme-raed/pull/293  `Repository rule violations found

You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.

 ❌`

-------------------


Merged by: @jalmatari

**Comment by SallaDev** [comment]
https://github.com/SallaApp/theme-raed/pull/293  `Repository rule violations found

You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.

 ❌`

-------------------


Merged by: @jalmatari

**Comment by SallaDev** [comment]
https://github.com/SallaApp/theme-raed/pull/293  `Repository rule violations found

You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.

 ❌`

-------------------


Merged by: @jalmatari

**Comment by SallaDev** [comment]
https://github.com/SallaApp/theme-raed/pull/293 ` is been merged ✅`

-------------------


Merged by: @jalmatari

**Pull request merged**
