### PR TITLE
 feat(themes):✨ Support new twilight components 

### PR DESCRIPTION
**Pull request by eslamoo**
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* Feature

What is the current behaviour? (You can also link to an open issue here)

* The logic for many areas Rendered from backend

What is the new behaviour? (You can also link to the ticket here)

* Support New Twilight Components Using `salla.config` and Ajax requests
  * `salla-social`
  * `salla-menu`
  * `salla-contacts`
  * `salla-social`
  * `salla-apps-icons`
  * `salla-payments`
  * `salla-advertisement`
  * `salla-comments`

### CODE REVIEW

**Comment by SallaDev** [comment]
> The branch `feature/support-new-twilight-components` of https://github.com/SallaApp/theme-raed/pull/274 has Merge conflict❌.

**Comment by SallaDev** [comment]
> The branch `feature/support-new-twilight-components` of https://github.com/SallaApp/theme-raed/pull/274 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `feature/support-new-twilight-components` of https://github.com/SallaApp/theme-raed/pull/274 Branch is up-to-date..✅

**Comment by SallaDev** [comment]
> The branch `feature/support-new-twilight-components` of https://github.com/SallaApp/theme-raed/pull/274 Branch is up-to-date..✅

**Review by jalmatari — APPROVED** [review]

**Review by jalmatari — APPROVED** [review]

**Comment by SallaDev** [comment]
https://github.com/SallaApp/theme-raed/pull/274 is been merged ✅

-------------------

Merge by: @jalmatari

**Pull request merged**
