### PR TITLE
fix(themes): display text 'out of stock ' with-unavailable-Option

### PR DESCRIPTION
**Pull request by ashrafreda**
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* bug fix 

What is the current behaviour? (You can also link to an open issue here)

* if product with unavailable option , there was no updates on price 

What is the new behaviour? (You can also link to the ticket here)

* we display sentence 'out of stock' if product has  unavailable option

Does this PR introduce a breaking change?

* no

Screenshots (If appropriate)

*

### CODE REVIEW

**Review by Ahmed-S-Abduallah — APPROVED** [review]

**Review by jalmatari — APPROVED** [review]

**Comment by SallaDev** [comment]
**Status Checks:**
- Please make sure  `Codacy Static Code Analysis` of (https://github.com/SallaApp/theme-raed/pull/433) is passed  ❌.

Merge by: @jalmatari

**Comment by SallaDev** [comment]
https://github.com/SallaApp/theme-raed/pull/433 is been merged ✅

-------------------

Merge by: @jalmatari

**Pull request merged**
