### PR TITLE
feat(themes): 📝 Blog Interaction

### PR DESCRIPTION
**Pull request by eslamoo**
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* Feature

What is the current behaviour? (You can also link to an open issue here)

* https://salla-dev.atlassian.net/browse/STORE-1848

What is the new behaviour? (You can also link to the ticket here)

* https://salla-dev.atlassian.net/browse/STORE-1848

Does this PR introduce a breaking change?

* No

Screenshots (If appropriate)

*

### CODE REVIEW

**Comment by SallaDev** [comment]
> The branch `feature/STORE-1848-blog-interaction` of https://github.com/SallaApp/theme-raed/pull/429 Branch is up-to-date..✅

**Comment by SallaDev** [comment]
> The branch `feature/STORE-1848-blog-interaction` of https://github.com/SallaApp/theme-raed/pull/429 Branch is up-to-date..✅

**Comment by SallaDev** [comment]
> The branch `feature/STORE-1848-blog-interaction` of https://github.com/SallaApp/theme-raed/pull/429 Branch is up-to-date..✅

**Comment by SallaDev** [comment]
> The branch `feature/STORE-1848-blog-interaction` of https://github.com/SallaApp/theme-raed/pull/429 Branch is up-to-date..✅

**Review by jalmatari — APPROVED** [review]

**Comment by SallaDev** [comment]
https://github.com/SallaApp/theme-raed/pull/429 is been merged ✅

-------------------

Merge by: @jalmatari

**Pull request merged**
