### PR TITLE
feat(themes): handle when cart option is applied to different categories

### PR DESCRIPTION
**Pull request by Ahmed-Basalib10**
- handle the case when the cart option is applied to different categories and update the DOM accordingly

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* Update

What is the current behaviour? (You can also link to an open issue here)

* Not handling the case when cart option is applied to diffrent categories

What is the new behaviour? (You can also link to the ticket here)

* we are handling the case when cart option is applied to diffrent categories

Does this PR introduce a breaking change?

* No

Screenshots (If appropriate)

*

### CODE REVIEW

**Review by jalmatari — APPROVED** [review]

**Comment by SallaDev** [comment]
**Status Checks:**
- Please make sure  `Codacy Static Code Analysis` of (https://github.com/SallaApp/theme-raed/pull/315) is passed  ❌.

Merge by: @jalmatari

**Review by jalmatari — APPROVED** [review]

**Review by jalmatari — APPROVED** [review]

**Comment by SallaDev** [comment]
https://github.com/SallaApp/theme-raed/pull/315 is been merged ✅

-------------------

Merge by: @jalmatari

**Pull request merged**
