### PR TITLE
Revert "feat(themes): ✨ Support Using `source`, `source_value` in home components"

### PR DESCRIPTION
**Pull request by devlomingo**
Reverts SallaApp/theme-raed#309

### CODE REVIEW

**Comment by SallaDev** [comment]
**Approve:**
- can not merge pr (https://github.com/SallaApp/theme-raed/pull/384) needs at least `one approve ❗️`



Merge by: @jalmatari

**Review by jalmatari — APPROVED** [review]

**Comment by SallaDev** [comment]
https://github.com/SallaApp/theme-raed/pull/384 is been merged ✅

-------------------

Merge by: @jalmatari

**Pull request merged**
