### PR TITLE
themes-enhances-fixes

### PR DESCRIPTION
**Pull request by egkrinkel**
Related Store Pr: https://github.com/SallaApp/Store/pull/4234
Related Task: https://app.clickup.com/t/8669anz2j

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* 

What is the current behaviour? (You can also link to an open issue here)

* 

What is the new behaviour? (You can also link to the ticket here)

* 

Does this PR introduce a breaking change?

* 

Screenshots (If appropriate)

*

### CODE REVIEW

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Comment by SallaDev** [comment]
> The branch `themes-enhances-fixes` of https://github.com/SallaApp/theme-raed/pull/184 has been synced from master..✅

**Review by jalmatari — APPROVED** [review]

**Pull request merged**
