### PR TITLE
feat(themes): ✨ Support Using `source`, `source_value` in home components

### PR DESCRIPTION
**Pull request by jalmatari**
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* Refactor

What is the current behaviour? (You can also link to an open issue here)

* We are getting the products from backend using `products|map...ect` in components `fixed-products`, `products-slider`

What is the new behaviour? (You can also link to the ticket here)

* supporting getting the products using `source` and `source_value`

Does this PR introduce a breaking change?

* No (but we are changing the products prop, now it's deprecated, we still support the old way, but soon will not be available)

Screenshots (If appropriate)

*

### CODE REVIEW

**Comment by SallaDev** [comment]
> The branch `feature/THEM-00-use-source-source_value` of https://github.com/SallaApp/theme-raed/pull/309 Branch is up-to-date..✅

**Comment by SallaDev** [comment]
> The branch `feature/THEM-00-use-source-source_value` of https://github.com/SallaApp/theme-raed/pull/309 Branch is up-to-date..✅

**Review by bakrimoharram — APPROVED** [review]

**Pull request merged**
