### PR TITLE
refactor(themes): Remove Deprecated Code

### PR DESCRIPTION
**Pull request by jalmatari**
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* Remove Deprecated code

What is the current behaviour? (You can also link to an open issue here)

* showing old supported data on the comments

What is the new behaviour? (You can also link to the ticket here)

* removing the deprecated object from the comments, before removing all of it's usages in the code

Does this PR introduce a breaking change?

* No

Screenshots (If appropriate)

*

### CODE REVIEW

**Comment by SallaDev** [comment]
**Approve:**
- can not merge pr (https://github.com/SallaApp/theme-raed/pull/305) needs at least `one approve ❗️`



Merge by: @jalmatari

**Review by devlomingo — APPROVED** [review]

**Review by devlomingo — APPROVED** [review]

**Comment by SallaDev** [comment]
https://github.com/SallaApp/theme-raed/pull/305 is been merged ✅

-------------------

Merge by: @jalmatari

**Pull request merged**
